version: '3.2'
services:
  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-mercury
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
      - ./upload:/upload
  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    command: [tail, -f, "/dev/null"]
    container_name: test_runner
    volumes:
      - ./test:/test
      - ./upload:/upload
    environment:
      - API_TOKEN=680ab152595077377dae0a980b327ed7791c137b
